### ISSUE TITLE
secret_token.rb should be, well, secret

### ISSUE THREAD

**Issue by ottopoellath** [adcloud/peerreview#6]
`config/initializers/secret_token.rb` [is like a root key for your application. If you have the secret token, it is trivial to forge sessions and escalate privileges](http://blog.codeclimate.com/blog/2013/03/27/rails-insecure-defaults/#versioned-secrets).

It should therefore not be publicly visible on GitHub.

**Comment by luebken** [comment]
now injected via env: https://github.com/adcloud/peerreview/commit/974d12686dd97545f2e78564c8333b40f0739da1
